#!/bin/bash
#SBATCH --qos=debug
# ^ see more on QOS (https://docs.nersc.gov/jobs/policy/#selecting-a-queue)
#SBATCH --time=5
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --constraint=cpu
# ^ note these are all just arbitrarily here from example (https://docs.nersc.gov/jobs/examples/)

# This is the command that ceci had printed, with a few modifications. Note:
#    - Updated the .yml, _config.yml (chunk_size: 10000 -> 10)
#    - Data is now training, not validation
#OMP_NUM_THREADS=1 mpirun -n 4 python3 -m ceci rail.estimation.algos.random_gauss.RandomGaussEstimator --input=training_100gal.hdf5 --name=rg_estimate --config=random_gauss_config.yml --output=./output_rg_estimate.hdf5 --mpi


# now for UBC
OMP_NUM_THREADS=1 mpirun -n 4 python3 -m ceci rail.estimation.algos.uniform_binning.UniformBinningClassifier   --input=output_BPZ_lite.hdf5   --name=ub_classify   --config=tmp_uniform_binning_config.yml   --output=./output_ub_classify.hdf5 --mpi

# try the simple version, which used to be fine from bash, but now exits with status -9
#OMP_NUM_THREADS=1 python3 -m ceci rail.estimation.algos.uniform_binning.UniformBinningClassifier   --input=output_BPZ_lite.hdf5 --name=ub_classify   --config=tmp_uniform_binning_config.yml   --output=./output_ub_classify.hdf5 --mpi
#OMP_NUM_THREADS=1 python3 -m ceci rail.estimation.algos.uniform_binning.UniformBinningClassifier   --input=output_BPZ_lite.hdf5 --name=ub_classify   --config=tmp_uniform_binning_config.yml   --output=./output_ub_classify.hdf5

#ceci tmp_uniform_binning.yml