config: tmp_goldenspike_config.yml
inputs:
  model: /global/u2/q/qhang/desc/rail_base/src/rail/examples_data/goldenspike_data/data/pretrained_flow.pkl
log_dir: .
modules: rail
output_dir: .
resume: false
site:
  max_threads: 2
stages:
- classname: FlowCreator
  module_name: rail.creation.engines.flowEngine
  name: flow_engine_train
  nprocess: 1
- classname: LSSTErrorModel
  module_name: rail.creation.degradation.lsst_error_model
  name: lsst_error_model_train
  nprocess: 1
- classname: InvRedshiftIncompleteness
  module_name: rail.creation.degradation.spectroscopic_degraders
  name: inv_redshift
  nprocess: 1
- classname: LineConfusion
  module_name: rail.creation.degradation.spectroscopic_degraders
  name: line_confusion
  nprocess: 1
- classname: QuantityCut
  module_name: rail.creation.degradation.quantityCut
  name: quantity_cut
  nprocess: 1
- classname: ColumnMapper
  module_name: rail.core.utilStages
  name: col_remapper_train
  nprocess: 1
- classname: TableConverter
  module_name: rail.core.utilStages
  name: table_conv_train
  nprocess: 1
- classname: FlowCreator
  module_name: rail.creation.engines.flowEngine
  name: flow_engine_test
  nprocess: 1
- classname: LSSTErrorModel
  module_name: rail.creation.degradation.lsst_error_model
  name: lsst_error_model_test
  nprocess: 1
- classname: ColumnMapper
  module_name: rail.core.utilStages
  name: col_remapper_test
  nprocess: 1
- classname: TableConverter
  module_name: rail.core.utilStages
  name: table_conv_test
  nprocess: 1
- classname: KNearNeighInformer
  module_name: rail.estimation.algos.k_nearneigh
  name: inform_knn
  nprocess: 1
- classname: FlexZBoostInformer
  module_name: rail.estimation.algos.flexzboost
  name: inform_fzboost
  nprocess: 1
- classname: BPZliteInformer
  module_name: rail.estimation.algos.bpz_lite
  name: inform_bpz
  nprocess: 1
- classname: BPZliteEstimator
  module_name: rail.estimation.algos.bpz_lite
  name: estimate_bpz
  nprocess: 1
- classname: KNearNeighEstimator
  module_name: rail.estimation.algos.k_nearneigh
  name: estimate_knn
  nprocess: 1
- classname: FlexZBoostEstimator
  module_name: rail.estimation.algos.flexzboost
  name: estimate_fzboost
  nprocess: 1
- classname: Evaluator
  module_name: rail.evaluation.evaluator
  name: bpz_eval
  nprocess: 1
- classname: Evaluator
  module_name: rail.evaluation.evaluator
  name: fzboost_eval
  nprocess: 1
- classname: Evaluator
  module_name: rail.evaluation.evaluator
  name: knn_eval
  nprocess: 1
- classname: PointEstHistSummarizer
  module_name: rail.estimation.algos.point_est_hist
  name: point_estimate_test
  nprocess: 1
- classname: NaiveStackSummarizer
  module_name: rail.estimation.algos.naive_stack
  name: naive_stack_test
  nprocess: 1
