bpz_eval:
  aliases:
    input: output_estimate_bpz
    output: output_bpz_eval
    truth: output_flow_engine_train
  config: null
  do_cde: true
  input: None
  name: bpz_eval
  nzbins: 301
  output: pdf/pz/output_bpz_eval.pq
  output_mode: default
  pit_metrics: all
  point_metrics: all
  truth: None
  zmax: 3.0
  zmin: 0.0
col_remapper_test:
  aliases:
    input: output_lsst_error_model_test
    output: output_col_remapper_test
  chunk_size: 100000
  columns: &id001
    mag_g_lsst_err: mag_err_g_lsst
    mag_i_lsst_err: mag_err_i_lsst
    mag_r_lsst_err: mag_err_r_lsst
    mag_u_lsst_err: mag_err_u_lsst
    mag_y_lsst_err: mag_err_y_lsst
    mag_z_lsst_err: mag_err_z_lsst
  config: null
  inplace: false
  input: None
  name: col_remapper_test
  output: catalog/degraded/output_col_remapper_test.pq
  output_mode: default
col_remapper_train:
  aliases:
    input: output_quantity_cut
    output: output_col_remapper_train
  chunk_size: 100000
  columns: *id001
  config: null
  inplace: false
  input: None
  name: col_remapper_train
  output: catalog/degraded/output_col_remapper_train.pq
  output_mode: default
estimate_bpz:
  aliases:
    input: output_table_conv_test
    model: model_inform_bpz
    output: output_estimate_bpz
  bands: &id002
  - mag_u_lsst
  - mag_g_lsst
  - mag_r_lsst
  - mag_i_lsst
  - mag_z_lsst
  - mag_y_lsst
  calculated_point_estimates: &id003 []
  chunk_size: 10000
  columns_file: /global/u2/q/qhang/desc/rail_bpz/src/rail/examples_data/estimation_data/configs/test_bpz.columns
  config: null
  data_path: None
  dz: 0.01
  err_bands: &id004
  - mag_err_u_lsst
  - mag_err_g_lsst
  - mag_err_r_lsst
  - mag_err_i_lsst
  - mag_err_z_lsst
  - mag_err_y_lsst
  gauss_kernel: 0.0
  hdf5_groupname: ''
  input: None
  madau_flag: 'no'
  mag_err_min: 0.005
  mag_limits: &id005
    mag_g_lsst: 29.04
    mag_i_lsst: 28.62
    mag_r_lsst: 29.06
    mag_u_lsst: 27.79
    mag_y_lsst: 27.05
    mag_z_lsst: 27.98
  model: None
  name: estimate_bpz
  no_prior: true
  nondetect_val: 99.0
  nzbins: 301
  output: pdf/pz/output_estimate_bpz.hdf5
  output_mode: default
  p_min: 0.005
  redshift_col: redshift
  ref_band: mag_i_lsst
  spectra_file: CWWSB4.list
  unobserved_val: -99.0
  zmax: 3.0
  zmin: 0.0
  zp_errors:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
estimate_fzboost:
  aliases:
    input: output_table_conv_test
    model: model_inform_fzboost
    output: output_estimate_fzboost
  bands: *id002
  calculated_point_estimates: *id003
  chunk_size: 10000
  config: null
  err_bands: *id004
  hdf5_groupname: ''
  input: None
  mag_limits: *id005
  model: None
  name: estimate_fzboost
  nondetect_val: .nan
  nzbins: 301
  output: pdf/pz/output_estimate_FZBoost.hdf5
  output_mode: default
  qp_representation: interp
  ref_band: mag_i_lsst
estimate_knn:
  aliases:
    input: output_table_conv_test
    model: model_inform_knn
    output: output_estimate_knn
  bands: *id002
  calculated_point_estimates: *id003
  chunk_size: 10000
  config: null
  hdf5_groupname: ''
  input: None
  mag_limits: *id005
  model: None
  name: estimate_knn
  nondetect_val: .nan
  nzbins: 301
  output: pdf/pz/output_estimate_knn.hdf5
  output_mode: default
  redshift_col: redshift
  ref_band: mag_i_lsst
  zmax: 3.0
  zmin: 0.0
flow_engine_test:
  aliases:
    output: output_flow_engine_test
  config: null
  model: /global/u2/q/qhang/desc/rail_base/src/rail/examples_data/goldenspike_data/data/pretrained_flow.pkl
  n_samples: 50
  name: flow_engine_test
  output: catalog/degraded/output_flow_engine_test.pq
  output_mode: default
  seed: 12345
flow_engine_train:
  aliases:
    output: output_flow_engine_train
  config: null
  model: /global/u2/q/qhang/desc/rail_base/src/rail/examples_data/goldenspike_data/data/pretrained_flow.pkl
  n_samples: 50
  name: flow_engine_train
  output: catalog/created/output_flow_engine_train.pq
  output_mode: default
  seed: 1235
fzboost_eval:
  aliases:
    input: output_estimate_fzboost
    output: output_fzboost_eval
    truth: output_flow_engine_train
  config: null
  do_cde: true
  input: None
  name: fzboost_eval
  nzbins: 301
  output: pdf/pz/output_fzboost_eval.pq
  output_mode: default
  pit_metrics: all
  point_metrics: all
  truth: None
  zmax: 3.0
  zmin: 0.0
inform_bpz:
  aliases:
    input: output_table_conv_train
    model: model_inform_bpz
  bands: *id002
  columns_file: /global/u2/q/qhang/desc/rail_bpz/src/rail/examples_data/estimation_data/configs/test_bpz.columns
  config: null
  data_path: None
  err_bands: *id004
  hdf5_groupname: ''
  init_alpha: 1.8
  init_km: 0.1
  init_kt: 0.3
  init_zo: 0.4
  input: None
  m0: 20.0
  mag_limits: *id005
  mmax: 26.0
  mmin: 18.0
  model: model/estimator/trained_BPZ.pkl
  name: inform_bpz
  nondetect_val: 99.0
  nt_array:
  - 8
  nzbins: 301
  output_mode: default
  redshift_col: redshift
  ref_band: mag_i_lsst
  save_train: true
  spectra_file: CWWSB4.list
  type_file: ''
  zmax: 3.0
  zmin: 0.0
inform_fzboost:
  aliases:
    input: output_table_conv_train
    model: model_inform_fzboost
  bands: *id002
  basis_system: cosine
  bumpmax: 0.35
  bumpmin: 0.02
  config: null
  err_bands: *id004
  hdf5_groupname: ''
  input: None
  mag_limits: *id005
  max_basis: 35
  model: model/estimator/fzboost.pkl
  name: inform_fzboost
  nbump: 20
  nondetect_val: 99.0
  nsharp: 15
  nzbins: 301
  output_mode: default
  redshift_col: redshift
  ref_band: mag_i_lsst
  regression_params:
    max_depth: 8
    objective: reg:squarederror
  retrain_full: true
  save_train: true
  seed: 1138
  sharpmax: 2.1
  sharpmin: 0.7
  trainfrac: 0.75
  zmax: 3.0
  zmin: 0.0
inform_knn:
  aliases:
    input: output_table_conv_train
    model: model_inform_knn
  bands: *id002
  config: null
  hdf5_groupname: ''
  input: None
  leaf_size: 15
  mag_limits: *id005
  model: model/estimator/knnpz.pkl
  name: inform_knn
  ngrid_sigma: 10
  nneigh_max: 7
  nneigh_min: 3
  nondetect_val: .nan
  nzbins: 301
  output_mode: default
  redshift_col: redshift
  ref_band: mag_i_lsst
  save_train: true
  seed: 0
  sigma_grid_max: 0.075
  sigma_grid_min: 0.01
  trainfrac: 0.75
  zmax: 3.0
  zmin: 0.0
inv_redshift:
  aliases:
    input: output_lsst_error_model_train
    output: output_inv_redshift
  config: null
  input: None
  name: inv_redshift
  output: catalog/degraded/output_inv_redshift.pq
  output_mode: default
  pivot_redshift: 1.0
  seed: 12345
knn_eval:
  aliases:
    input: output_estimate_knn
    output: output_knn_eval
    truth: output_flow_engine_train
  config: null
  do_cde: true
  input: None
  name: knn_eval
  nzbins: 301
  output: pdf/pz/output_knn_eval.pq
  output_mode: default
  pit_metrics: all
  point_metrics: all
  truth: None
  zmax: 3.0
  zmin: 0.0
line_confusion:
  aliases:
    input: output_inv_redshift
    output: output_line_confusion
  config: null
  frac_wrong: 0.05
  input: None
  name: line_confusion
  output: catalog/degraded/output_line_confusion.pq
  output_mode: default
  seed: 12345
  true_wavelen: 5007.0
  wrong_wavelen: 3727.0
lsst_error_model_test:
  Cm: &id006
    g: 24.42
    i: 24.32
    r: 24.44
    u: 23.09
    y: 23.73
    z: 24.16
  aMax: 2.0
  aMin: 0.7
  absFlux: false
  airmass: 1.2
  aliases:
    input: output_flow_engine_test
    output: output_lsst_error_model_test
  bandNames: &id012
    g: mag_g_lsst
    i: mag_i_lsst
    r: mag_r_lsst
    u: mag_u_lsst
    y: mag_y_lsst
    z: mag_z_lsst
  config: null
  decorrelate: true
  errLoc: after
  extendedType: point
  gamma: &id007
    g: 0.039
    i: 0.039
    r: 0.039
    u: 0.038
    y: 0.039
    z: 0.039
  highSNR: false
  input: None
  km: &id008
    g: 0.213
    i: 0.096
    r: 0.126
    u: 0.491
    y: 0.17
    z: 0.069
  m5: &id009 {}
  majorCol: major
  minorCol: minor
  msky: &id010
    g: 22.26
    i: 20.48
    r: 21.2
    u: 22.99
    y: 18.61
    z: 19.6
  nVisYr: &id011
    g: 8.0
    i: 18.4
    r: 18.4
    u: 5.6
    y: 16.0
    z: 16.0
  nYrObs: 10.0
  name: lsst_error_model_test
  ndFlag: .inf
  ndMode: flag
  output: catalog/degraded/output_lsst_error_model_test.pq
  output_mode: default
  renameDict: null
  scale: &id013 {}
  seed: 12345
  sigLim: 0
  sigmaSys: 0.005
  theta: &id014
    g: 0.77
    i: 0.71
    r: 0.73
    u: 0.81
    y: 0.68
    z: 0.69
  tvis: 30.0
  validate: true
lsst_error_model_train:
  Cm: *id006
  aMax: 2.0
  aMin: 0.7
  absFlux: false
  airmass: 1.2
  aliases:
    input: output_flow_engine_train
    output: output_lsst_error_model_train
  config: null
  decorrelate: true
  errLoc: after
  extendedType: point
  gamma: *id007
  highSNR: false
  input: None
  km: *id008
  m5: *id009
  majorCol: major
  minorCol: minor
  msky: *id010
  nVisYr: *id011
  nYrObs: 10.0
  name: lsst_error_model_train
  ndFlag: .inf
  ndMode: flag
  output: catalog/degraded/output_lsst_error_model_train.pq
  output_mode: default
  renameDict: *id012
  scale: *id013
  seed: 29
  sigLim: 0
  sigmaSys: 0.005
  theta: *id014
  tvis: 30.0
  validate: true
naive_stack_test:
  aliases:
    input: output_estimate_bpz
    output: output_naive_stack_test
    single_NZ: single_NZ_naive_stack_test
  chunk_size: 10000
  config: null
  input: None
  name: naive_stack_test
  nsamples: 1000
  nzbins: 301
  output: pdf/nz/output_naive_stack_test.hdf5
  output_mode: default
  seed: 87
  single_NZ: pdf/nz/single_NZ_naive_stack_test.hdf5
  zmax: 3.0
  zmin: 0.0
point_estimate_test:
  aliases:
    input: output_estimate_bpz
    output: output_point_estimate_test
    single_NZ: single_NZ_point_estimate_test
  chunk_size: 10000
  config: null
  input: None
  name: point_estimate_test
  nsamples: 1000
  nzbins: 301
  output: pdf/nz/output_point_estimate_test.hdf5
  output_mode: default
  point_estimate: zmode
  seed: 87
  single_NZ: pdf/nz/single_NZ_point_estimate_test.hdf5
  zmax: 3.0
  zmin: 0.0
quantity_cut:
  aliases:
    input: output_line_confusion
    output: output_quantity_cut
  config: null
  cuts:
    mag_i_lsst: 25.0
  input: None
  name: quantity_cut
  output: catalog/degraded/output_quantity_cut.pq
  output_mode: default
  seed: 12345
table_conv_test:
  aliases:
    input: output_col_remapper_test
    output: output_table_conv_test
  config: null
  input: None
  name: table_conv_test
  output: catalog/degraded/output_table_conv_test.hdf5
  output_format: numpyDict
  output_mode: default
table_conv_train:
  aliases:
    input: output_col_remapper_train
    output: output_table_conv_train
  config: null
  input: None
  name: table_conv_train
  output: catalog/degraded/output_table_conv_train.hdf5
  output_format: numpyDict
  output_mode: default
