col_remapper_train:
  aliases:
    input: output_obs_condition
    output: output_col_remapper_train
  chunk_size: 100000
  columns:
    mag_g_lsst_err: mag_err_g_lsst
    mag_i_lsst_err: mag_err_i_lsst
    mag_r_lsst_err: mag_err_r_lsst
    mag_u_lsst_err: mag_err_u_lsst
    mag_y_lsst_err: mag_err_y_lsst
    mag_z_lsst_err: mag_err_z_lsst
  config: null
  inplace: false
  input: None
  name: col_remapper_train
  output: catalog/degraded/output_col_remapper_train.pq
  output_mode: default
deredden:
  aliases:
    input: output_col_remapper_train
    output: output_deredden
  band_a_env:
  - 4.81
  - 3.64
  - 2.7
  - 2.06
  - 1.58
  - 1.31
  bands: ugrizy
  config: null
  copy_cols: []
  dustmap_dir: .
  dustmap_name: sfd
  input: None
  mag_name: mag_{band}_lsst
  name: deredden
  output: catalog/degraded/output_deredden.pq
  output_mode: default
estimate_bpz:
  aliases:
    input: output_deredden
    model: model_inform_bpz
    output: output_estimate_bpz
  bands: &id001
  - mag_u_lsst
  - mag_g_lsst
  - mag_r_lsst
  - mag_i_lsst
  - mag_z_lsst
  - mag_y_lsst
  calculated_point_estimates: []
  chunk_size: 10000
  columns_file: /global/u2/q/qhang/desc/rail_bpz/src/rail/examples_data/estimation_data/configs/test_bpz.columns
  config: null
  data_path: None
  dz: 0.01
  err_bands: &id002
  - mag_err_u_lsst
  - mag_err_g_lsst
  - mag_err_r_lsst
  - mag_err_i_lsst
  - mag_err_z_lsst
  - mag_err_y_lsst
  gauss_kernel: 0.0
  hdf5_groupname: ''
  input: None
  madau_flag: 'no'
  mag_err_min: 0.005
  mag_limits: &id003
    mag_g_lsst: 29.04
    mag_i_lsst: 28.62
    mag_r_lsst: 29.06
    mag_u_lsst: 27.79
    mag_y_lsst: 27.05
    mag_z_lsst: 27.98
  model: None
  name: estimate_bpz
  no_prior: true
  nondetect_val: 99.0
  nzbins: 301
  output: pdf/pz/output_estimate_bpz.hdf5
  output_mode: default
  p_min: 0.005
  redshift_col: redshift
  ref_band: mag_i_lsst
  spectra_file: CWWSB4.list
  unobserved_val: -99.0
  zmax: 3.0
  zmin: 0.0
  zp_errors:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
flow_engine_train:
  aliases:
    output: output_flow_engine_train
  config: null
  model: /global/u2/q/qhang/desc/rail_base/src/rail/examples_data/goldenspike_data/data/pretrained_flow.pkl
  n_samples: 10
  name: flow_engine_train
  output: catalog/created/output_flow_engine_train.pq
  output_mode: default
  seed: 12345
inform_bpz:
  aliases:
    input: output_deredden
    model: model_inform_bpz
  bands: *id001
  columns_file: /global/u2/q/qhang/desc/rail_bpz/src/rail/examples_data/estimation_data/configs/test_bpz.columns
  config: null
  data_path: None
  err_bands: *id002
  hdf5_groupname: ''
  init_alpha: 1.8
  init_km: 0.1
  init_kt: 0.3
  init_zo: 0.4
  input: None
  m0: 20.0
  mag_limits: *id003
  mmax: 26.0
  mmin: 18.0
  model: model/estimator/trained_BPZ.pkl
  name: inform_bpz
  nondetect_val: 99.0
  nt_array:
  - 8
  nzbins: 301
  output_mode: default
  redshift_col: redshift
  ref_band: mag_i_lsst
  save_train: true
  spectra_file: CWWSB4.list
  type_file: ''
  zmax: 3.0
  zmin: 0.0
obs_condition:
  aliases:
    input: output_flow_engine_train
    output: output_obs_condition
  config: null
  input: None
  map_dict:
    m5:
      i: /global/u2/q/qhang/desc/rail_astro_tools/src/rail/creation/degradation/../../examples_data/creation_data/data/survey_conditions/minion_1016_dc2_Median_fiveSigmaDepth_i_and_nightlt1825_HEAL.fits
    nYrObs: 5.0
  mask: /global/u2/q/qhang/desc/rail_astro_tools/src/rail/creation/degradation/../../examples_data/creation_data/data/survey_conditions/DC2-mask-neg-nside-128.fits
  name: obs_condition
  nside: 128
  output: catalog/degraded/output_obscondition.pq
  output_mode: default
  random_seed: 42
  seed: 12345
  tot_nVis_flag: true
  weight: /global/u2/q/qhang/desc/rail_astro_tools/src/rail/creation/degradation/../../examples_data/creation_data/data/survey_conditions/DC2-dr6-galcounts-i20-i25.3-nside-128.fits
tomopraphy:
  aliases:
    input: output_estimate_bpz
    output: output_tomopraphy
  chunk_size: 10000
  config: null
  id_name: ''
  input: None
  name: tomopraphy
  nbins: 5
  no_assign: -99
  output: pdf/pz/output_tomography.hdf5
  output_mode: default
  point_estimate: zmode
  zbin_edges: []
  zmax: 3.0
  zmin: 0.0
